-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 14:29:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VirtualGym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VirtualGym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VirtualGym` DEFAULT CHARACTER SET utf8 ;
USE `VirtualGym` ;

-- -----------------------------------------------------
-- Table `VirtualGym`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(32) NOT NULL,
  `bairro` VARCHAR(32) NOT NULL,
  `cidade` VARCHAR(32) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `complemento` VARCHAR(10) NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `Endereco_idEndereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  INDEX `fk_Usuario_Endereco1_idx` (`Endereco_idEndereco` ASC) ,
  CONSTRAINT `fk_Usuario_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `VirtualGym`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Aluno` (
  `idAluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `responsavel` VARCHAR(40) NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Aluno_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VirtualGym`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Administrador` (
  `idAdministrador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataAdmissao` DATE NOT NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VirtualGym`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Professor` (
  `idProfessor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataAdmissao` DATE NOT NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProfessor`),
  INDEX `fk_Professor_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VirtualGym`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`FichaTreino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`FichaTreino` (
  `idFichaTreino` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NOT NULL,
  `dataReavaliacao` DATE NOT NULL,
  `dias` VARCHAR(7) NULL,
  `observacao` VARCHAR(100) NULL,
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  `Professor_idProfessor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFichaTreino`),
  INDEX `fk_FichaTreino_Aluno1_idx` (`Aluno_idAluno` ASC) ,
  INDEX `fk_FichaTreino_Professor1_idx` (`Professor_idProfessor` ASC) ,
  CONSTRAINT `fk_FichaTreino_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `VirtualGym`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FichaTreino_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `VirtualGym`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Plano` (
  `idPlano` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `taxaAdesao` FLOAT UNSIGNED NOT NULL,
  `parcelas` TINYINT UNSIGNED NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `taxaJuros` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPlano`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Pagamento` (
  `idPagamento` INT ZEROFILL UNSIGNED NOT NULL,
  `tipoPagamento` TINYINT UNSIGNED NOT NULL,
  `parcelas` TINYINT UNSIGNED NOT NULL,
  `juros` FLOAT UNSIGNED NOT NULL,
  `valorPagamento` FLOAT UNSIGNED NOT NULL,
  `dataPagamento` DATE NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`MatriculaAcademia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`MatriculaAcademia` (
  `idMatriculaAcademia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataMatricula` DATE NOT NULL,
  `diaVencimento` TINYINT UNSIGNED NOT NULL,
  `Plano_idPlano` INT UNSIGNED NOT NULL,
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMatriculaAcademia`),
  INDEX `fk_MatriculaAcademia_Plano1_idx` (`Plano_idPlano` ASC) ,
  INDEX `fk_MatriculaAcademia_Aluno1_idx` (`Aluno_idAluno` ASC) ,
  UNIQUE INDEX `Aluno_idAluno_UNIQUE` (`Aluno_idAluno` ASC) ,
  CONSTRAINT `fk_MatriculaAcademia_Plano1`
    FOREIGN KEY (`Plano_idPlano`)
    REFERENCES `VirtualGym`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatriculaAcademia_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `VirtualGym`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`RelatorioMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`RelatorioMatricula` (
  `idRelatorioMatricula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `MatriculaAcademia_idMatriculaAcademia` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRelatorioMatricula`),
  INDEX `fk_RelatorioMatricula_MatriculaAcademia1_idx` (`MatriculaAcademia_idMatriculaAcademia` ASC) ,
  CONSTRAINT `fk_RelatorioMatricula_MatriculaAcademia1`
    FOREIGN KEY (`MatriculaAcademia_idMatriculaAcademia`)
    REFERENCES `VirtualGym`.`MatriculaAcademia` (`idMatriculaAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Entrada` (
  `idEntrada` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataEntrada` DATE NOT NULL,
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEntrada`),
  INDEX `fk_Entrada_Aluno1_idx` (`Aluno_idAluno` ASC) ,
  CONSTRAINT `fk_Entrada_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `VirtualGym`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`RelatorioFrequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`RelatorioFrequencia` (
  `idRelatorioFrequencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `periodo` DATE NOT NULL,
  `Entrada_idEntrada` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRelatorioFrequencia`),
  INDEX `fk_RelatorioFrequencia_Entrada1_idx` (`Entrada_idEntrada` ASC) ,
  CONSTRAINT `fk_RelatorioFrequencia_Entrada1`
    FOREIGN KEY (`Entrada_idEntrada`)
    REFERENCES `VirtualGym`.`Entrada` (`idEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`AvaliacaoFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`AvaliacaoFisica` (
  `idAvaliacaoFisica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataAvaliacao` DATE NOT NULL,
  `dataReavaliacao` DATE NOT NULL,
  `peso` FLOAT UNSIGNED NULL,
  `altura` FLOAT UNSIGNED NULL,
  `perimetroTorax` FLOAT UNSIGNED NULL,
  `perimetroQuadril` FLOAT UNSIGNED NULL,
  `perimetroAbdomen` FLOAT UNSIGNED NULL,
  `perimetroCintura` FLOAT UNSIGNED NULL,
  `perimetroAntebracoDireito` FLOAT UNSIGNED NULL,
  `perimetroAntebracoEsquerdo` FLOAT UNSIGNED NULL,
  `perimetroBracoDireito` FLOAT UNSIGNED NULL,
  `perimetroBracoEsquerdo` FLOAT UNSIGNED NULL,
  `perimetroCoxaDireita` FLOAT UNSIGNED NULL,
  `perimetroCoxaEsquerda` FLOAT UNSIGNED NULL,
  `perimetroPanturrilhaDireita` FLOAT UNSIGNED NULL,
  `perimetroPanturrilhaEsquerda` FLOAT UNSIGNED NULL,
  `dobraSubescapular` FLOAT UNSIGNED NULL,
  `dobraTricipital` FLOAT UNSIGNED NULL,
  `dobraPeitoral` FLOAT UNSIGNED NULL,
  `dobraAbdominal` FLOAT UNSIGNED NULL,
  `dobraSuprailiaca` FLOAT UNSIGNED NULL,
  `dobraCoxaDireita` FLOAT UNSIGNED NULL,
  `dobraCoxaEsquerda` FLOAT UNSIGNED NULL,
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  `Professor_idProfessor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAvaliacaoFisica`),
  INDEX `fk_AvaliacaoFisica_Aluno1_idx` (`Aluno_idAluno` ASC) ,
  INDEX `fk_AvaliacaoFisica_Professor1_idx` (`Professor_idProfessor` ASC) ,
  CONSTRAINT `fk_AvaliacaoFisica_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `VirtualGym`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AvaliacaoFisica_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `VirtualGym`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`RelatorioAvaliacaoFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`RelatorioAvaliacaoFisica` (
  `idRelatorioAvaliacaoFisica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `AvaliacaoFisica_idAvaliacaoFisica` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRelatorioAvaliacaoFisica`),
  INDEX `fk_RelatorioAvaliacaoFisica_AvaliacaoFisica1_idx` (`AvaliacaoFisica_idAvaliacaoFisica` ASC) ,
  CONSTRAINT `fk_RelatorioAvaliacaoFisica_AvaliacaoFisica1`
    FOREIGN KEY (`AvaliacaoFisica_idAvaliacaoFisica`)
    REFERENCES `VirtualGym`.`AvaliacaoFisica` (`idAvaliacaoFisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Aula` (
  `idAula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `taxaJuros` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Sala` (
  `idSala` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `capacidade` TINYINT UNSIGNED NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `nome` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Turma` (
  `idTurma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Professor_idProfessor` INT UNSIGNED NOT NULL,
  `Sala_idSala` INT UNSIGNED NOT NULL,
  `Aula_idAula` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `fk_Turma_Professor1_idx` (`Professor_idProfessor` ASC) ,
  INDEX `fk_Turma_Sala1_idx` (`Sala_idSala` ASC) ,
  INDEX `fk_Turma_Aula1_idx` (`Aula_idAula` ASC) ,
  CONSTRAINT `fk_Turma_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `VirtualGym`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `VirtualGym`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `VirtualGym`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`MatriculaAula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`MatriculaAula` (
  `idMatriculaAula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataMatricula` DATE NOT NULL,
  `diaVencimento` TINYINT UNSIGNED NOT NULL,
  `Aluno_idAluno` INT UNSIGNED NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMatriculaAula`),
  INDEX `fk_MatriculaAula_Aluno1_idx` (`Aluno_idAluno` ASC) ,
  INDEX `fk_MatriculaAula_Turma1_idx` (`Turma_idTurma` ASC) ,
  CONSTRAINT `fk_MatriculaAula_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `VirtualGym`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatriculaAula_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `VirtualGym`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Exercicio` (
  `idExercicio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `tipoTreino` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idExercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Aerobico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Aerobico` (
  `idAerobico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordem` TINYINT UNSIGNED NOT NULL,
  `tempo` TINYINT UNSIGNED NOT NULL,
  `distancia` TINYINT UNSIGNED NOT NULL,
  `FichaTreino_idFichaTreino` INT UNSIGNED NOT NULL,
  `Exercicio_idExercicio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAerobico`),
  INDEX `fk_Aerobico_FichaTreino1_idx` (`FichaTreino_idFichaTreino` ASC) ,
  INDEX `fk_Aerobico_Exercicio1_idx` (`Exercicio_idExercicio` ASC) ,
  CONSTRAINT `fk_Aerobico_FichaTreino1`
    FOREIGN KEY (`FichaTreino_idFichaTreino`)
    REFERENCES `VirtualGym`.`FichaTreino` (`idFichaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aerobico_Exercicio1`
    FOREIGN KEY (`Exercicio_idExercicio`)
    REFERENCES `VirtualGym`.`Exercicio` (`idExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Musculacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Musculacao` (
  `idMusculacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordem` TINYINT UNSIGNED NOT NULL,
  `series` TINYINT UNSIGNED NOT NULL,
  `peso` SMALLINT UNSIGNED NOT NULL,
  `repeticoes` TINYINT UNSIGNED NOT NULL,
  `FichaTreino_idFichaTreino` INT UNSIGNED NOT NULL,
  `Exercicio_idExercicio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMusculacao`),
  INDEX `fk_Musculacao_FichaTreino1_idx` (`FichaTreino_idFichaTreino` ASC) ,
  INDEX `fk_Musculacao_Exercicio1_idx` (`Exercicio_idExercicio` ASC) ,
  CONSTRAINT `fk_Musculacao_FichaTreino1`
    FOREIGN KEY (`FichaTreino_idFichaTreino`)
    REFERENCES `VirtualGym`.`FichaTreino` (`idFichaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musculacao_Exercicio1`
    FOREIGN KEY (`Exercicio_idExercicio`)
    REFERENCES `VirtualGym`.`Exercicio` (`idExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`PagamentoPlano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`PagamentoPlano` (
  `idPagamentoPlano` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MatriculaAcademia_idMatriculaAcademia` INT UNSIGNED NOT NULL,
  `Pagamento_idPagamento` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`idPagamentoPlano`),
  INDEX `fk_PagamentoPlano_MatriculaAcademia1_idx` (`MatriculaAcademia_idMatriculaAcademia` ASC) ,
  INDEX `fk_PagamentoPlano_Pagamento1_idx` (`Pagamento_idPagamento` ASC) ,
  CONSTRAINT `fk_PagamentoPlano_MatriculaAcademia1`
    FOREIGN KEY (`MatriculaAcademia_idMatriculaAcademia`)
    REFERENCES `VirtualGym`.`MatriculaAcademia` (`idMatriculaAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PagamentoPlano_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `VirtualGym`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`PagamentoAula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`PagamentoAula` (
  `idPagamentoAula` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MatriculaAula_idMatriculaAula` INT UNSIGNED NOT NULL,
  `Pagamento_idPagamento` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`idPagamentoAula`),
  INDEX `fk_PagamentoAula_MatriculaAula1_idx` (`MatriculaAula_idMatriculaAula` ASC) ,
  INDEX `fk_PagamentoAula_Pagamento1_idx` (`Pagamento_idPagamento` ASC) ,
  CONSTRAINT `fk_PagamentoAula_MatriculaAula1`
    FOREIGN KEY (`MatriculaAula_idMatriculaAula`)
    REFERENCES `VirtualGym`.`MatriculaAula` (`idMatriculaAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PagamentoAula_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `VirtualGym`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VirtualGym`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VirtualGym`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(7) NOT NULL,
  `horaInicio` CHAR(5) NOT NULL,
  `horaFim` CHAR(5) NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horario_Turma1_idx` (`Turma_idTurma` ASC) ,
  CONSTRAINT `fk_Horario_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `VirtualGym`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
